name: flutter_udid
description: Plugin to retrieve a persistent UDID across reinstalls on iOS and Android
version: 4.0.1  # Incremented version number to indicate your fix
homepage: https://github.com/ibrahemsayed/flutter_udid  # Update with your GitHub username
repository: https://github.com/ibrahemsayed/flutter_udid  # Update with your GitHub username
issue_tracker: https://github.com/ibrahemsayed/flutter_udid/issues  # Update with your GitHub username

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: de.gigadroid.flutter_udid
        pluginClass: FlutterUdidPlugin
      ios:
        pluginClass: FlutterUdidPlugin
      macos:
        pluginClass: FlutterUdidPlugin
      windows:
        pluginClass: FlutterUdidPluginCApi
      linux:
        pluginClass: FlutterUdidPlugin
